server:
  port: 8090

spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.30.134:8848
dubbo:
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: provider
#  consumer:
#    loadbalance: roundrobin
#  provider:
#    loadbalance: roundrobin
